import { createContext, useContext, useState, ReactNode, useCallback } from "react";

export type LangCode = "pt" | "en" | "es" | "fr" | "de" | "it" | "zh" | "ja" | "ko" | "ar" | "hi" | "ru";

export const languages: { code: LangCode; label: string; name: string }[] = [
  { code: "pt", label: "PT", name: "Português" },
  { code: "en", label: "EN", name: "English" },
  { code: "es", label: "ES", name: "Español" },
  { code: "fr", label: "FR", name: "Français" },
  { code: "de", label: "DE", name: "Deutsch" },
  { code: "it", label: "IT", name: "Italiano" },
  { code: "zh", label: "中文", name: "中文" },
  { code: "ja", label: "日本", name: "日本語" },
  { code: "ko", label: "한국", name: "한국어" },
  { code: "ar", label: "عربي", name: "العربية" },
  { code: "hi", label: "हिंदी", name: "हिंदी" },
  { code: "ru", label: "RU", name: "Русский" },
];

type TranslationKey =
  | "trends" | "moreTrends" | "filters" | "country" | "countries" | "period" | "category" | "type"
  | "global" | "lastHour" | "today" | "thisWeek" | "thisMonth"
  | "all" | "politics" | "entertainment" | "technology" | "sports" | "culture" | "business" | "science"
  | "allMedia" | "socialMedia" | "press" | "searches"
  | "live" | "peak" | "copied" | "updated" | "about" | "aboutTitle" | "aboutDesc"
  | "map" | "satellite" | "terrain" | "timeline" | "clickToClose"
  | "trendCount" | "loading" | "expandDetails" | "evolution24h" | "share" | "noTrends"
  | "heatmapDensity" | "low" | "high"
  | "views" | "upvotes" | "comments" | "interactions" | "likes"
  | "officialSource" | "scientific" | "international" | "localPress"
  | "watchOn" | "viewOn" | "readOn" | "viewSource" | "summarizeAI" | "analyzing"
  | "aiSummary" | "impactHigh" | "impactMedium" | "impactLow"
  | "showing" | "filterCategory" | "filterSource" | "critical" | "lastUpdate" | "viewSourceStatus"
  | "backToTop" | "tryChangingFilters" | "noTrendsCurrentFilters" | "supportTool" | "support"
  // Card-specific keys
  | "verifiedPress" | "scientificData" | "internationalSource" | "hotTopic"
  | "positive" | "negative" | "neutral"
  | "launch" | "crisis" | "declaration" | "sportsEvent" | "scienceEvent" | "businessEvent"
  | "startedAgo" | "peakAt"
  | "linkCopied" | "linkCopiedDesc" | "loginRequired" | "loginRequiredDesc"
  | "error" | "alertCreated" | "monitoring" | "errorSummarize" | "tryAgain"
  | "filterByPlatform" | "copyLinkFilters" | "createAlert"
  | "tabDetails" | "tabContext" | "tabHistory"
  | "general" | "autoTranslated"
  | "loginTitle" | "loginSubtitle" | "continueWithGoogle" | "continueWithApple" | "connecting"
  | "termsIntro" | "termsOfUse" | "privacyPolicy" | "allFeaturesFree" | "enter";

const translations: Record<LangCode, Record<TranslationKey, string>> = {
  pt: {
    trends: "Tendências", moreTrends: "Mais trends", filters: "Filtros",
    country: "País", period: "Período", category: "Categoria", type: "Tipo",
    global: "Global", lastHour: "Última hora", today: "Hoje", thisWeek: "Esta semana", thisMonth: "Este mês",
    all: "Todas", politics: "Política", entertainment: "Entretenimento", technology: "Tecnologia",
    sports: "Esportes", culture: "Cultura", business: "Negócios/Finanças", science: "Ciência",
    allMedia: "Todas mídias", socialMedia: "Redes sociais", press: "Imprensa", searches: "Buscas (Google)",
    live: "ao vivo", peak: "PICO", copied: "Copiado!", updated: "Atualizado",
    about: "Sobre", aboutTitle: "Global-Talk-Trending",
    aboutDesc: "Monitor de tendências globais em tempo real. Agregamos dados do YouTube, Reddit, Google Trends e NewsAPI para oferecer uma visão completa do que está em alta no mundo.",
    map: "Mapa", satellite: "Satélite", terrain: "Terreno", timeline: "Timeline",
    clickToClose: "Clique para fechar", trendCount: "trends", loading: "Carregando...",
    expandDetails: "Ver detalhes", evolution24h: "Evolução 24h", share: "Compartilhar", noTrends: "Sem tendências",
    heatmapDensity: "Densidade de Trends", low: "Baixo", high: "Alto",
    views: "visualizações", upvotes: "upvotes", comments: "comentários", interactions: "interações", likes: "curtidas",
    officialSource: "Fonte Oficial", scientific: "Acadêmico/Científico", international: "Internacional", localPress: "Imprensa",
    watchOn: "Assistir no", viewOn: "Ver no", readOn: "Ler no", viewSource: "Ver fonte original", summarizeAI: "Resumir com IA", analyzing: "Analisando...",
    aiSummary: "Resumo IA", impactHigh: "Alto", impactMedium: "Médio", impactLow: "Baixo",
    countries: "Países", showing: "Mostrando", filterCategory: "Categoria", filterSource: "Fonte",
    critical: "CRÍTICOS", lastUpdate: "Última atualização", viewSourceStatus: "Ver status das fontes",
    backToTop: "Voltar ao topo", tryChangingFilters: "Tente mudar o período ou os filtros, ou volte mais tarde.",
    noTrendsCurrentFilters: "Nenhuma trend encontrada com os filtros atuais.", supportTool: "Apoie a melhoria contínua da ferramenta", support: "Apoie",
    verifiedPress: "Imprensa Verificada", scientificData: "Dados Científicos", internationalSource: "Fonte Internacional", hotTopic: "PAUTA QUENTE",
    positive: "Positivo", negative: "Negativo", neutral: "Neutro",
    launch: "Lançamento", crisis: "Crise", declaration: "Declaração", sportsEvent: "Esportes", scienceEvent: "Ciência", businessEvent: "Negócios",
    startedAgo: "Começou há", peakAt: "Pico às",
    linkCopied: "Link copiado!", linkCopiedDesc: "Link com filtros atuais copiado.",
    loginRequired: "Faça login", loginRequiredDesc: "Login necessário para criar alertas.",
    error: "Erro", alertCreated: "Alerta criado!", monitoring: "Monitorando",
    errorSummarize: "Erro ao resumir", tryAgain: "Tente novamente.",
    filterByPlatform: "Filtrar por", copyLinkFilters: "Copiar link com filtros", createAlert: "Criar alerta",
    tabDetails: "Detalhes", tabContext: "Contexto", tabHistory: "Histórico",
    general: "Geral", autoTranslated: "Traduzido automaticamente",
    loginTitle: "Entrar no Global Talk Trends", loginSubtitle: "Acesse para salvar filtros e receber alertas",
    continueWithGoogle: "Continuar com Google", continueWithApple: "Continuar com Apple", connecting: "Conectando…",
    termsIntro: "Ao continuar, você concorda com nossos", termsOfUse: "Termos de Uso", privacyPolicy: "Política de Privacidade",
    allFeaturesFree: "Todas as funcionalidades são gratuitas", enter: "Entrar",
  },
  en: {
    trends: "Trends", moreTrends: "More trends", filters: "Filters",
    country: "Country", period: "Period", category: "Category", type: "Type",
    global: "Global", lastHour: "Last hour", today: "Today", thisWeek: "This week", thisMonth: "This month",
    all: "All", politics: "Politics", entertainment: "Entertainment", technology: "Technology",
    sports: "Sports", culture: "Culture", business: "Business/Finance", science: "Science",
    allMedia: "All media", socialMedia: "Social media", press: "Press", searches: "Search (Google)",
    live: "live", peak: "PEAK", copied: "Copied!", updated: "Updated",
    about: "About", aboutTitle: "Global-Talk-Trending",
    aboutDesc: "Real-time global trends monitor. We aggregate data from YouTube, Reddit, Google Trends, and NewsAPI to provide a complete view of what's trending worldwide.",
    map: "Map", satellite: "Satellite", terrain: "Terrain", timeline: "Timeline",
    clickToClose: "Click to close", trendCount: "trends", loading: "Loading...",
    expandDetails: "View details", evolution24h: "24h Evolution", share: "Share", noTrends: "No trends",
    heatmapDensity: "Trend Density", low: "Low", high: "High",
    views: "views", upvotes: "upvotes", comments: "comments", interactions: "interactions", likes: "likes",
    officialSource: "Official Source", scientific: "Academic/Scientific", international: "International", localPress: "Press",
    watchOn: "Watch on", viewOn: "View on", readOn: "Read on", viewSource: "View original source", summarizeAI: "Summarize with AI", analyzing: "Analyzing...",
    aiSummary: "AI Summary", impactHigh: "High", impactMedium: "Medium", impactLow: "Low",
    countries: "Countries", showing: "Showing", filterCategory: "Category", filterSource: "Source",
    critical: "CRITICAL", lastUpdate: "Last update", viewSourceStatus: "View source status",
    backToTop: "Back to top", tryChangingFilters: "Try changing the period or filters, or come back later.",
    noTrendsCurrentFilters: "No trends found with current filters.", supportTool: "Support the continuous improvement of this tool", support: "Support",
    verifiedPress: "Verified Press", scientificData: "Scientific Data", internationalSource: "International Source", hotTopic: "HOT TOPIC",
    positive: "Positive", negative: "Negative", neutral: "Neutral",
    launch: "Launch", crisis: "Crisis", declaration: "Statement", sportsEvent: "Sports", scienceEvent: "Science", businessEvent: "Business",
    startedAgo: "Started", peakAt: "Peak at",
    linkCopied: "Link copied!", linkCopiedDesc: "Link with current filters copied.",
    loginRequired: "Log in", loginRequiredDesc: "Login required to create alerts.",
    error: "Error", alertCreated: "Alert created!", monitoring: "Monitoring",
    errorSummarize: "Error summarizing", tryAgain: "Try again.",
    filterByPlatform: "Filter by", copyLinkFilters: "Copy link with filters", createAlert: "Create alert",
    tabDetails: "Details", tabContext: "Context", tabHistory: "History",
    general: "General", autoTranslated: "Auto-translated",
    loginTitle: "Sign in to Global Talk Trends", loginSubtitle: "Access to save filters and receive alerts",
    continueWithGoogle: "Continue with Google", continueWithApple: "Continue with Apple", connecting: "Connecting…",
    termsIntro: "By continuing, you agree to our", termsOfUse: "Terms of Use", privacyPolicy: "Privacy Policy",
    allFeaturesFree: "All features are free", enter: "Sign in",
  },
  es: {
    trends: "Tendencias", moreTrends: "Más trends", filters: "Filtros",
    country: "País", period: "Período", category: "Categoría", type: "Tipo",
    global: "Global", lastHour: "Última hora", today: "Hoy", thisWeek: "Esta semana", thisMonth: "Este mes",
    all: "Todas", politics: "Política", entertainment: "Entretenimiento", technology: "Tecnología",
    sports: "Deportes", culture: "Cultura", business: "Negocios/Finanzas", science: "Ciencia",
    allMedia: "Todos los medios", socialMedia: "Redes sociales", press: "Prensa", searches: "Búsquedas (Google)",
    live: "en vivo", peak: "PICO", copied: "¡Copiado!", updated: "Actualizado",
    about: "Acerca de", aboutTitle: "Global-Talk-Trending",
    aboutDesc: "Monitor de tendencias globales en tiempo real. Agregamos datos de YouTube, Reddit, Google Trends y NewsAPI.",
    map: "Mapa", satellite: "Satélite", terrain: "Terreno", timeline: "Timeline",
    clickToClose: "Clic para cerrar", trendCount: "tendencias", loading: "Cargando...",
    expandDetails: "Ver detalles", evolution24h: "Evolución 24h", share: "Compartir", noTrends: "Sin tendencias",
    heatmapDensity: "Densidad de Trends", low: "Bajo", high: "Alto",
    views: "visualizaciones", upvotes: "upvotes", comments: "comentarios", interactions: "interacciones", likes: "me gusta",
    officialSource: "Fuente Oficial", scientific: "Académico/Científico", international: "Internacional", localPress: "Prensa",
    watchOn: "Ver en", viewOn: "Ver en", readOn: "Leer en", viewSource: "Ver fuente original", summarizeAI: "Resumir con IA", analyzing: "Analizando...",
    aiSummary: "Resumen IA", impactHigh: "Alto", impactMedium: "Medio", impactLow: "Bajo",
    countries: "Países", showing: "Mostrando", filterCategory: "Categoría", filterSource: "Fuente",
    critical: "CRÍTICOS", lastUpdate: "Última actualización", viewSourceStatus: "Ver estado de fuentes",
    backToTop: "Volver arriba", tryChangingFilters: "Intente cambiar el período o los filtros.",
    noTrendsCurrentFilters: "No se encontraron tendencias con los filtros actuales.", supportTool: "Apoya la mejora continua de la herramienta", support: "Apoyar",
    verifiedPress: "Prensa Verificada", scientificData: "Datos Científicos", internationalSource: "Fuente Internacional", hotTopic: "TEMA CANDENTE",
    positive: "Positivo", negative: "Negativo", neutral: "Neutro",
    launch: "Lanzamiento", crisis: "Crisis", declaration: "Declaración", sportsEvent: "Deportes", scienceEvent: "Ciencia", businessEvent: "Negocios",
    startedAgo: "Empezó hace", peakAt: "Pico a las",
    linkCopied: "¡Enlace copiado!", linkCopiedDesc: "Enlace con filtros actuales copiado.",
    loginRequired: "Inicia sesión", loginRequiredDesc: "Se requiere login para crear alertas.",
    error: "Error", alertCreated: "¡Alerta creada!", monitoring: "Monitoreando",
    errorSummarize: "Error al resumir", tryAgain: "Inténtalo de nuevo.",
    filterByPlatform: "Filtrar por", copyLinkFilters: "Copiar enlace con filtros", createAlert: "Crear alerta",
    tabDetails: "Detalles", tabContext: "Contexto", tabHistory: "Historial",
    general: "General", autoTranslated: "Traducido automáticamente",
    loginTitle: "Entrar en Global Talk Trends", loginSubtitle: "Accede para guardar filtros y recibir alertas",
    continueWithGoogle: "Continuar con Google", continueWithApple: "Continuar con Apple", connecting: "Conectando…",
    termsIntro: "Al continuar, aceptas nuestros", termsOfUse: "Términos de Uso", privacyPolicy: "Política de Privacidad",
    allFeaturesFree: "Todas las funcionalidades son gratuitas", enter: "Entrar",
  },
  fr: {
    trends: "Tendances", moreTrends: "Plus de tendances", filters: "Filtres",
    country: "Pays", period: "Période", category: "Catégorie", type: "Type",
    global: "Mondial", lastHour: "Dernière heure", today: "Aujourd'hui", thisWeek: "Cette semaine", thisMonth: "Ce mois",
    all: "Toutes", politics: "Politique", entertainment: "Divertissement", technology: "Technologie",
    sports: "Sports", culture: "Culture", business: "Affaires/Finance", science: "Science",
    allMedia: "Tous les médias", socialMedia: "Réseaux sociaux", press: "Presse", searches: "Recherches (Google)",
    live: "en direct", peak: "PIC", copied: "Copié !", updated: "Mis à jour",
    about: "À propos", aboutTitle: "Global-Talk-Trending",
    aboutDesc: "Moniteur de tendances mondiales en temps réel. Nous agrégeons des données de YouTube, Reddit, Google Trends et NewsAPI.",
    map: "Carte", satellite: "Satellite", terrain: "Terrain", timeline: "Timeline",
    clickToClose: "Cliquer pour fermer", trendCount: "tendances", loading: "Chargement...",
    expandDetails: "Voir les détails", evolution24h: "Évolution 24h", share: "Partager", noTrends: "Aucune tendance",
    heatmapDensity: "Densité des Trends", low: "Faible", high: "Élevé",
    views: "vues", upvotes: "upvotes", comments: "commentaires", interactions: "interactions", likes: "j'aime",
    officialSource: "Source Officielle", scientific: "Académique/Scientifique", international: "International", localPress: "Presse",
    watchOn: "Regarder sur", viewOn: "Voir sur", readOn: "Lire sur", viewSource: "Voir source originale", summarizeAI: "Résumer avec IA", analyzing: "Analyse...",
    aiSummary: "Résumé IA", impactHigh: "Élevé", impactMedium: "Moyen", impactLow: "Faible",
    countries: "Pays", showing: "Affichage", filterCategory: "Catégorie", filterSource: "Source",
    critical: "CRITIQUES", lastUpdate: "Dernière mise à jour", viewSourceStatus: "Voir statut des sources",
    backToTop: "Retour en haut", tryChangingFilters: "Essayez de modifier la période ou les filtres.",
    noTrendsCurrentFilters: "Aucune tendance trouvée avec les filtres actuels.", supportTool: "Soutenez l'amélioration continue de l'outil", support: "Soutenir",
    verifiedPress: "Presse Vérifiée", scientificData: "Données Scientifiques", internationalSource: "Source Internationale", hotTopic: "SUJET BRÛLANT",
    positive: "Positif", negative: "Négatif", neutral: "Neutre",
    launch: "Lancement", crisis: "Crise", declaration: "Déclaration", sportsEvent: "Sports", scienceEvent: "Science", businessEvent: "Affaires",
    startedAgo: "Commencé il y a", peakAt: "Pic à",
    linkCopied: "Lien copié !", linkCopiedDesc: "Lien avec filtres actuels copié.",
    loginRequired: "Connectez-vous", loginRequiredDesc: "Connexion requise pour créer des alertes.",
    error: "Erreur", alertCreated: "Alerte créée !", monitoring: "Surveillance",
    errorSummarize: "Erreur de résumé", tryAgain: "Réessayez.",
    filterByPlatform: "Filtrer par", copyLinkFilters: "Copier le lien avec filtres", createAlert: "Créer une alerte",
    tabDetails: "Détails", tabContext: "Contexte", tabHistory: "Historique",
    general: "Général", autoTranslated: "Traduit automatiquement",
    loginTitle: "Se connecter à Global Talk Trends", loginSubtitle: "Accédez pour sauvegarder vos filtres et recevoir des alertes",
    continueWithGoogle: "Continuer avec Google", continueWithApple: "Continuer avec Apple", connecting: "Connexion…",
    termsIntro: "En continuant, vous acceptez nos", termsOfUse: "Conditions d'utilisation", privacyPolicy: "Politique de confidentialité",
    allFeaturesFree: "Toutes les fonctionnalités sont gratuites", enter: "Connexion",
  },
  de: {
    trends: "Trends", moreTrends: "Mehr Trends", filters: "Filter",
    country: "Land", period: "Zeitraum", category: "Kategorie", type: "Typ",
    global: "Global", lastHour: "Letzte Stunde", today: "Heute", thisWeek: "Diese Woche", thisMonth: "Diesen Monat",
    all: "Alle", politics: "Politik", entertainment: "Unterhaltung", technology: "Technologie",
    sports: "Sport", culture: "Kultur", business: "Wirtschaft/Finanzen", science: "Wissenschaft",
    allMedia: "Alle Medien", socialMedia: "Soziale Medien", press: "Presse", searches: "Suche (Google)",
    live: "live", peak: "PEAK", copied: "Kopiert!", updated: "Aktualisiert",
    about: "Über", aboutTitle: "Global-Talk-Trending",
    aboutDesc: "Echtzeit-Monitor für globale Trends. Wir aggregieren Daten von YouTube, Reddit, Google Trends und NewsAPI.",
    map: "Karte", satellite: "Satellit", terrain: "Gelände", timeline: "Timeline",
    clickToClose: "Klicken zum Schließen", trendCount: "Trends", loading: "Laden...",
    expandDetails: "Details anzeigen", evolution24h: "24h-Entwicklung", share: "Teilen", noTrends: "Keine Trends",
    heatmapDensity: "Trend-Dichte", low: "Niedrig", high: "Hoch",
    views: "Aufrufe", upvotes: "Upvotes", comments: "Kommentare", interactions: "Interaktionen", likes: "Likes",
    officialSource: "Offizielle Quelle", scientific: "Akademisch/Wissenschaftlich", international: "International", localPress: "Presse",
    watchOn: "Ansehen auf", viewOn: "Ansehen auf", readOn: "Lesen auf", viewSource: "Originalquelle ansehen", summarizeAI: "Mit KI zusammenfassen", analyzing: "Analyse...",
    aiSummary: "KI-Zusammenfassung", impactHigh: "Hoch", impactMedium: "Mittel", impactLow: "Niedrig",
    countries: "Länder", showing: "Anzeige", filterCategory: "Kategorie", filterSource: "Quelle",
    critical: "KRITISCH", lastUpdate: "Letzte Aktualisierung", viewSourceStatus: "Quellenstatus anzeigen",
    backToTop: "Nach oben", tryChangingFilters: "Versuchen Sie, den Zeitraum oder die Filter zu ändern.",
    noTrendsCurrentFilters: "Keine Trends mit aktuellen Filtern gefunden.", supportTool: "Unterstützen Sie die kontinuierliche Verbesserung", support: "Unterstützen",
    verifiedPress: "Verifizierte Presse", scientificData: "Wissenschaftliche Daten", internationalSource: "Internationale Quelle", hotTopic: "HEISSES THEMA",
    positive: "Positiv", negative: "Negativ", neutral: "Neutral",
    launch: "Veröffentlichung", crisis: "Krise", declaration: "Erklärung", sportsEvent: "Sport", scienceEvent: "Wissenschaft", businessEvent: "Wirtschaft",
    startedAgo: "Begonnen vor", peakAt: "Höhepunkt um",
    linkCopied: "Link kopiert!", linkCopiedDesc: "Link mit aktuellen Filtern kopiert.",
    loginRequired: "Anmelden", loginRequiredDesc: "Anmeldung erforderlich für Alarme.",
    error: "Fehler", alertCreated: "Alarm erstellt!", monitoring: "Überwachung",
    errorSummarize: "Fehler beim Zusammenfassen", tryAgain: "Erneut versuchen.",
    filterByPlatform: "Filtern nach", copyLinkFilters: "Link mit Filtern kopieren", createAlert: "Alarm erstellen",
    tabDetails: "Details", tabContext: "Kontext", tabHistory: "Verlauf",
    general: "Allgemein", autoTranslated: "Automatisch übersetzt",
    loginTitle: "Bei Global Talk Trends anmelden", loginSubtitle: "Zugang zum Speichern von Filtern und Erhalten von Benachrichtigungen",
    continueWithGoogle: "Weiter mit Google", continueWithApple: "Weiter mit Apple", connecting: "Verbinden…",
    termsIntro: "Durch Fortfahren stimmen Sie unseren zu", termsOfUse: "Nutzungsbedingungen", privacyPolicy: "Datenschutzrichtlinie",
    allFeaturesFree: "Alle Funktionen sind kostenlos", enter: "Anmelden",
  },
  it: {
    trends: "Tendenze", moreTrends: "Più tendenze", filters: "Filtri",
    country: "Paese", period: "Periodo", category: "Categoria", type: "Tipo",
    global: "Globale", lastHour: "Ultima ora", today: "Oggi", thisWeek: "Questa settimana", thisMonth: "Questo mese",
    all: "Tutte", politics: "Politica", entertainment: "Intrattenimento", technology: "Tecnologia",
    sports: "Sport", culture: "Cultura", business: "Affari/Finanza", science: "Scienza",
    allMedia: "Tutti i media", socialMedia: "Social media", press: "Stampa", searches: "Ricerche (Google)",
    live: "in diretta", peak: "PICCO", copied: "Copiato!", updated: "Aggiornato",
    about: "Info", aboutTitle: "Global-Talk-Trending",
    aboutDesc: "Monitor di tendenze globali in tempo reale. Aggreghiamo dati da YouTube, Reddit, Google Trends e NewsAPI.",
    map: "Mappa", satellite: "Satellite", terrain: "Terreno", timeline: "Timeline",
    clickToClose: "Clicca per chiudere", trendCount: "tendenze", loading: "Caricamento...",
    expandDetails: "Vedi dettagli", evolution24h: "Evoluzione 24h", share: "Condividi", noTrends: "Nessuna tendenza",
    heatmapDensity: "Densità dei Trend", low: "Basso", high: "Alto",
    views: "visualizzazioni", upvotes: "upvotes", comments: "commenti", interactions: "interazioni", likes: "mi piace",
    officialSource: "Fonte Ufficiale", scientific: "Accademico/Scientifico", international: "Internazionale", localPress: "Stampa",
    watchOn: "Guarda su", viewOn: "Vedi su", readOn: "Leggi su", viewSource: "Vedi fonte originale", summarizeAI: "Riassumi con IA", analyzing: "Analisi...",
    aiSummary: "Riassunto IA", impactHigh: "Alto", impactMedium: "Medio", impactLow: "Basso",
    countries: "Paesi", showing: "Visualizzazione", filterCategory: "Categoria", filterSource: "Fonte",
    critical: "CRITICI", lastUpdate: "Ultimo aggiornamento", viewSourceStatus: "Vedi stato fonti",
    backToTop: "Torna in alto", tryChangingFilters: "Prova a cambiare il periodo o i filtri.",
    noTrendsCurrentFilters: "Nessuna tendenza trovata con i filtri attuali.", supportTool: "Supporta il miglioramento continuo dello strumento", support: "Supporta",
    verifiedPress: "Stampa Verificata", scientificData: "Dati Scientifici", internationalSource: "Fonte Internazionale", hotTopic: "TEMA CALDO",
    positive: "Positivo", negative: "Negativo", neutral: "Neutro",
    launch: "Lancio", crisis: "Crisi", declaration: "Dichiarazione", sportsEvent: "Sport", scienceEvent: "Scienza", businessEvent: "Affari",
    startedAgo: "Iniziato", peakAt: "Picco alle",
    linkCopied: "Link copiato!", linkCopiedDesc: "Link con filtri attuali copiato.",
    loginRequired: "Accedi", loginRequiredDesc: "Login necessario per creare avvisi.",
    error: "Errore", alertCreated: "Avviso creato!", monitoring: "Monitoraggio",
    errorSummarize: "Errore nel riepilogo", tryAgain: "Riprova.",
    filterByPlatform: "Filtra per", copyLinkFilters: "Copia link con filtri", createAlert: "Crea avviso",
    tabDetails: "Dettagli", tabContext: "Contesto", tabHistory: "Storico",
    general: "Generale", autoTranslated: "Tradotto automaticamente",
    loginTitle: "Accedi a Global Talk Trends", loginSubtitle: "Accedi per salvare filtri e ricevere avvisi",
    continueWithGoogle: "Continua con Google", continueWithApple: "Continua con Apple", connecting: "Connessione…",
    termsIntro: "Continuando, accetti i nostri", termsOfUse: "Termini di utilizzo", privacyPolicy: "Informativa sulla privacy",
    allFeaturesFree: "Tutte le funzionalità sono gratuite", enter: "Accedi",
  },
  zh: {
    trends: "趋势", moreTrends: "更多趋势", filters: "筛选",
    country: "国家", period: "时段", category: "类别", type: "类型",
    global: "全球", lastHour: "最近一小时", today: "今天", thisWeek: "本周", thisMonth: "本月",
    all: "全部", politics: "政治", entertainment: "娱乐", technology: "科技",
    sports: "体育", culture: "文化", business: "商业/金融", science: "科学",
    allMedia: "所有媒体", socialMedia: "社交媒体", press: "新闻", searches: "搜索 (Google)",
    live: "直播", peak: "峰值", copied: "已复制！", updated: "已更新",
    about: "关于", aboutTitle: "Global-Talk-Trending",
    aboutDesc: "实时全球趋势监控器。我们汇总来自YouTube、Reddit、Google Trends和NewsAPI的数据。",
    map: "地图", satellite: "卫星", terrain: "地形", timeline: "时间线",
    clickToClose: "点击关闭", trendCount: "趋势", loading: "加载中...",
    expandDetails: "查看详情", evolution24h: "24小时演变", share: "分享", noTrends: "无趋势",
    heatmapDensity: "趋势密度", low: "低", high: "高",
    views: "浏览量", upvotes: "点赞", comments: "评论", interactions: "互动", likes: "喜欢",
    officialSource: "官方来源", scientific: "学术/科学", international: "国际", localPress: "新闻媒体",
    watchOn: "观看于", viewOn: "查看于", readOn: "阅读于", viewSource: "查看原始来源", summarizeAI: "AI总结", analyzing: "分析中...",
    aiSummary: "AI摘要", impactHigh: "高", impactMedium: "中", impactLow: "低",
    countries: "国家", showing: "显示", filterCategory: "类别", filterSource: "来源",
    critical: "紧急", lastUpdate: "最后更新", viewSourceStatus: "查看来源状态",
    backToTop: "返回顶部", tryChangingFilters: "尝试更改时间段或筛选条件。",
    noTrendsCurrentFilters: "当前筛选条件未找到趋势。", supportTool: "支持工具的持续改进", support: "支持",
    verifiedPress: "已验证新闻", scientificData: "科学数据", internationalSource: "国际来源", hotTopic: "热门话题",
    positive: "积极", negative: "消极", neutral: "中性",
    launch: "发布", crisis: "危机", declaration: "声明", sportsEvent: "体育", scienceEvent: "科学", businessEvent: "商业",
    startedAgo: "开始于", peakAt: "峰值于",
    linkCopied: "链接已复制！", linkCopiedDesc: "带有当前筛选条件的链接已复制。",
    loginRequired: "请登录", loginRequiredDesc: "需要登录才能创建警报。",
    error: "错误", alertCreated: "警报已创建！", monitoring: "监控中",
    errorSummarize: "摘要出错", tryAgain: "请重试。",
    filterByPlatform: "按平台筛选", copyLinkFilters: "复制带筛选链接", createAlert: "创建警报",
    tabDetails: "详情", tabContext: "背景", tabHistory: "历史",
    general: "综合", autoTranslated: "自动翻译",
    loginTitle: "登录 Global Talk Trends", loginSubtitle: "登录以保存筛选条件和接收提醒",
    continueWithGoogle: "使用 Google 继续", continueWithApple: "使用 Apple 继续", connecting: "连接中…",
    termsIntro: "继续即表示您同意我们的", termsOfUse: "使用条款", privacyPolicy: "隐私政策",
    allFeaturesFree: "所有功能均免费", enter: "登录",
  },
  ja: {
    trends: "トレンド", moreTrends: "もっと見る", filters: "フィルター",
    country: "国", period: "期間", category: "カテゴリー", type: "タイプ",
    global: "グローバル", lastHour: "直近1時間", today: "今日", thisWeek: "今週", thisMonth: "今月",
    all: "すべて", politics: "政治", entertainment: "エンタメ", technology: "テクノロジー",
    sports: "スポーツ", culture: "文化", business: "ビジネス/金融", science: "科学",
    allMedia: "全メディア", socialMedia: "SNS", press: "報道", searches: "検索 (Google)",
    live: "ライブ", peak: "ピーク", copied: "コピーしました！", updated: "更新済み",
    about: "について", aboutTitle: "Global-Talk-Trending",
    aboutDesc: "リアルタイムのグローバルトレンドモニター。YouTube、Reddit、Google Trends、NewsAPIからのデータを集約しています。",
    map: "マップ", satellite: "衛星", terrain: "地形", timeline: "タイムライン",
    clickToClose: "クリックして閉じる", trendCount: "トレンド", loading: "読み込み中...",
    expandDetails: "詳細を見る", evolution24h: "24時間の推移", share: "共有", noTrends: "トレンドなし",
    heatmapDensity: "トレンド密度", low: "低", high: "高",
    views: "再生回数", upvotes: "アップボート", comments: "コメント", interactions: "インタラクション", likes: "いいね",
    officialSource: "公式情報", scientific: "学術/科学", international: "国際", localPress: "報道",
    watchOn: "で視聴", viewOn: "で見る", readOn: "で読む", viewSource: "元の情報源を見る", summarizeAI: "AIで要約", analyzing: "分析中...",
    aiSummary: "AI要約", impactHigh: "高", impactMedium: "中", impactLow: "低",
    countries: "カ国", showing: "表示中", filterCategory: "カテゴリー", filterSource: "ソース",
    critical: "緊急", lastUpdate: "最終更新", viewSourceStatus: "ソース状態を表示",
    backToTop: "トップに戻る", tryChangingFilters: "期間やフィルターを変更してみてください。",
    noTrendsCurrentFilters: "現在のフィルターでトレンドが見つかりません。", supportTool: "ツールの継続的な改善を支援", support: "サポート",
    verifiedPress: "認証済み報道", scientificData: "科学データ", internationalSource: "国際情報源", hotTopic: "注目トピック",
    positive: "ポジティブ", negative: "ネガティブ", neutral: "ニュートラル",
    launch: "リリース", crisis: "危機", declaration: "声明", sportsEvent: "スポーツ", scienceEvent: "科学", businessEvent: "ビジネス",
    startedAgo: "開始", peakAt: "ピーク",
    linkCopied: "リンクコピー済み！", linkCopiedDesc: "現在のフィルター付きリンクをコピーしました。",
    loginRequired: "ログインしてください", loginRequiredDesc: "アラート作成にはログインが必要です。",
    error: "エラー", alertCreated: "アラート作成済み！", monitoring: "監視中",
    errorSummarize: "要約エラー", tryAgain: "再試行してください。",
    filterByPlatform: "プラットフォームで絞り込み", copyLinkFilters: "フィルター付きリンクをコピー", createAlert: "アラート作成",
    tabDetails: "詳細", tabContext: "コンテキスト", tabHistory: "履歴",
    general: "一般", autoTranslated: "自動翻訳済み",
    loginTitle: "Global Talk Trends にサインイン", loginSubtitle: "フィルターの保存やアラートの受信にアクセス",
    continueWithGoogle: "Google で続行", continueWithApple: "Apple で続行", connecting: "接続中…",
    termsIntro: "続行すると、以下に同意したことになります", termsOfUse: "利用規約", privacyPolicy: "プライバシーポリシー",
    allFeaturesFree: "すべての機能が無料です", enter: "サインイン",
  },
  ko: {
    trends: "트렌드", moreTrends: "더 많은 트렌드", filters: "필터",
    country: "국가", period: "기간", category: "카테고리", type: "유형",
    global: "글로벌", lastHour: "지난 1시간", today: "오늘", thisWeek: "이번 주", thisMonth: "이번 달",
    all: "전체", politics: "정치", entertainment: "엔터테인먼트", technology: "기술",
    sports: "스포츠", culture: "문화", business: "비즈니스/금융", science: "과학",
    allMedia: "모든 미디어", socialMedia: "소셜 미디어", press: "언론", searches: "검색 (Google)",
    live: "실시간", peak: "피크", copied: "복사됨!", updated: "업데이트됨",
    about: "소개", aboutTitle: "Global-Talk-Trending",
    aboutDesc: "실시간 글로벌 트렌드 모니터. YouTube, Reddit, Google Trends, NewsAPI의 데이터를 집계합니다.",
    map: "지도", satellite: "위성", terrain: "지형", timeline: "타임라인",
    clickToClose: "닫으려면 클릭", trendCount: "트렌드", loading: "로딩 중...",
    expandDetails: "상세 보기", evolution24h: "24시간 추이", share: "공유", noTrends: "트렌드 없음",
    heatmapDensity: "트렌드 밀도", low: "낮음", high: "높음",
    views: "조회수", upvotes: "추천", comments: "댓글", interactions: "상호작용", likes: "좋아요",
    officialSource: "공식 출처", scientific: "학술/과학", international: "국제", localPress: "언론",
    watchOn: "에서 시청", viewOn: "에서 보기", readOn: "에서 읽기", viewSource: "원본 소스 보기", summarizeAI: "AI로 요약", analyzing: "분석 중...",
    aiSummary: "AI 요약", impactHigh: "높음", impactMedium: "중간", impactLow: "낮음",
    countries: "개국", showing: "표시 중", filterCategory: "카테고리", filterSource: "출처",
    critical: "긴급", lastUpdate: "마지막 업데이트", viewSourceStatus: "소스 상태 보기",
    backToTop: "맨 위로", tryChangingFilters: "기간이나 필터를 변경해 보세요.",
    noTrendsCurrentFilters: "현재 필터로 트렌드를 찾을 수 없습니다.", supportTool: "도구의 지속적인 개선을 지원하세요", support: "지원",
    verifiedPress: "검증된 언론", scientificData: "과학 데이터", internationalSource: "국제 출처", hotTopic: "핫 토픽",
    positive: "긍정적", negative: "부정적", neutral: "중립",
    launch: "출시", crisis: "위기", declaration: "성명", sportsEvent: "스포츠", scienceEvent: "과학", businessEvent: "비즈니스",
    startedAgo: "시작됨", peakAt: "피크",
    linkCopied: "링크 복사됨!", linkCopiedDesc: "현재 필터가 포함된 링크가 복사되었습니다.",
    loginRequired: "로그인 필요", loginRequiredDesc: "알림 생성에 로그인이 필요합니다.",
    error: "오류", alertCreated: "알림 생성됨!", monitoring: "모니터링",
    errorSummarize: "요약 오류", tryAgain: "다시 시도하세요.",
    filterByPlatform: "플랫폼별 필터", copyLinkFilters: "필터 포함 링크 복사", createAlert: "알림 생성",
    tabDetails: "상세", tabContext: "맥락", tabHistory: "기록",
    general: "일반", autoTranslated: "자동 번역됨",
    loginTitle: "Global Talk Trends 로그인", loginSubtitle: "필터 저장 및 알림 수신을 위해 로그인하세요",
    continueWithGoogle: "Google로 계속", continueWithApple: "Apple로 계속", connecting: "연결 중…",
    termsIntro: "계속하면 다음에 동의하는 것입니다", termsOfUse: "이용약관", privacyPolicy: "개인정보 처리방침",
    allFeaturesFree: "모든 기능이 무료입니다", enter: "로그인",
  },
  ar: {
    trends: "الاتجاهات", moreTrends: "المزيد", filters: "التصفية",
    country: "البلد", period: "الفترة", category: "الفئة", type: "النوع",
    global: "عالمي", lastHour: "الساعة الأخيرة", today: "اليوم", thisWeek: "هذا الأسبوع", thisMonth: "هذا الشهر",
    all: "الكل", politics: "سياسة", entertainment: "ترفيه", technology: "تكنولوجيا",
    sports: "رياضة", culture: "ثقافة", business: "أعمال/مالية", science: "علوم",
    allMedia: "جميع الوسائط", socialMedia: "وسائل التواصل", press: "صحافة", searches: "بحث (Google)",
    live: "مباشر", peak: "ذروة", copied: "تم النسخ!", updated: "تم التحديث",
    about: "حول", aboutTitle: "Global-Talk-Trending",
    aboutDesc: "مراقب الاتجاهات العالمية في الوقت الفعلي.",
    map: "خريطة", satellite: "قمر صناعي", terrain: "تضاريس", timeline: "الجدول الزمني",
    clickToClose: "اضغط للإغلاق", trendCount: "اتجاهات", loading: "جار التحميل...",
    expandDetails: "عرض التفاصيل", evolution24h: "التطور 24 ساعة", share: "مشاركة", noTrends: "لا توجد اتجاهات",
    heatmapDensity: "كثافة الاتجاهات", low: "منخفض", high: "مرتفع",
    views: "مشاهدات", upvotes: "تصويت", comments: "تعليقات", interactions: "تفاعلات", likes: "إعجابات",
    officialSource: "مصدر رسمي", scientific: "أكاديمي/علمي", international: "دولي", localPress: "صحافة",
    watchOn: "شاهد على", viewOn: "عرض على", readOn: "اقرأ على", viewSource: "عرض المصدر الأصلي", summarizeAI: "تلخيص بالذكاء", analyzing: "جاري التحليل...",
    aiSummary: "ملخص ذكي", impactHigh: "مرتفع", impactMedium: "متوسط", impactLow: "منخفض",
    countries: "دول", showing: "عرض", filterCategory: "الفئة", filterSource: "المصدر",
    critical: "حرج", lastUpdate: "آخر تحديث", viewSourceStatus: "عرض حالة المصادر",
    backToTop: "العودة للأعلى", tryChangingFilters: "حاول تغيير الفترة أو الفلاتر.",
    noTrendsCurrentFilters: "لم يتم العثور على اتجاهات بالفلاتر الحالية.", supportTool: "ادعم التحسين المستمر للأداة", support: "دعم",
    verifiedPress: "صحافة موثقة", scientificData: "بيانات علمية", internationalSource: "مصدر دولي", hotTopic: "موضوع ساخن",
    positive: "إيجابي", negative: "سلبي", neutral: "محايد",
    launch: "إطلاق", crisis: "أزمة", declaration: "تصريح", sportsEvent: "رياضة", scienceEvent: "علوم", businessEvent: "أعمال",
    startedAgo: "بدأ منذ", peakAt: "الذروة في",
    linkCopied: "تم نسخ الرابط!", linkCopiedDesc: "تم نسخ الرابط مع الفلاتر الحالية.",
    loginRequired: "سجّل الدخول", loginRequiredDesc: "يجب تسجيل الدخول لإنشاء تنبيهات.",
    error: "خطأ", alertCreated: "تم إنشاء التنبيه!", monitoring: "مراقبة",
    errorSummarize: "خطأ في التلخيص", tryAgain: "حاول مجدداً.",
    filterByPlatform: "تصفية حسب", copyLinkFilters: "نسخ رابط مع فلاتر", createAlert: "إنشاء تنبيه",
    tabDetails: "تفاصيل", tabContext: "سياق", tabHistory: "تاريخ",
    general: "عام", autoTranslated: "مترجم تلقائيًا",
    loginTitle: "تسجيل الدخول إلى Global Talk Trends", loginSubtitle: "سجّل الدخول لحفظ الفلاتر واستقبال التنبيهات",
    continueWithGoogle: "المتابعة مع Google", continueWithApple: "المتابعة مع Apple", connecting: "جاري الاتصال…",
    termsIntro: "بالمتابعة، فإنك توافق على", termsOfUse: "شروط الاستخدام", privacyPolicy: "سياسة الخصوصية",
    allFeaturesFree: "جميع الميزات مجانية", enter: "دخول",
  },
  hi: {
    trends: "रुझान", moreTrends: "और रुझान", filters: "फ़िल्टर",
    country: "देश", period: "अवधि", category: "श्रेणी", type: "प्रकार",
    global: "वैश्विक", lastHour: "पिछला घंटा", today: "आज", thisWeek: "इस सप्ताह", thisMonth: "इस महीने",
    all: "सभी", politics: "राजनीति", entertainment: "मनोरंजन", technology: "तकनीक",
    sports: "खेल", culture: "संस्कृति", business: "व्यापार/वित्त", science: "विज्ञान",
    allMedia: "सभी मीडिया", socialMedia: "सोशल मीडिया", press: "प्रेस", searches: "खोज (Google)",
    live: "लाइव", peak: "शिखर", copied: "कॉपी किया!", updated: "अपडेट किया",
    about: "के बारे में", aboutTitle: "Global-Talk-Trending",
    aboutDesc: "रियल-टाइम ग्लोबल ट्रेंड मॉनिटर।",
    map: "मानचित्र", satellite: "उपग्रह", terrain: "भूभाग", timeline: "टाइमलाइन",
    clickToClose: "बंद करने के लिए क्लिक करें", trendCount: "रुझान", loading: "लोड हो रहा है...",
    expandDetails: "विवरण देखें", evolution24h: "24 घंटे का विकास", share: "शेयर", noTrends: "कोई रुझान नहीं",
    heatmapDensity: "रुझान घनत्व", low: "कम", high: "अधिक",
    views: "दृश्य", upvotes: "अपवोट", comments: "टिप्पणियाँ", interactions: "इंटरैक्शन", likes: "पसंद",
    officialSource: "आधिकारिक स्रोत", scientific: "अकादमिक/वैज्ञानिक", international: "अंतर्राष्ट्रीय", localPress: "प्रेस",
    watchOn: "पर देखें", viewOn: "पर देखें", readOn: "पर पढ़ें", viewSource: "मूल स्रोत देखें", summarizeAI: "AI से सारांश", analyzing: "विश्लेषण...",
    aiSummary: "AI सारांश", impactHigh: "उच्च", impactMedium: "मध्यम", impactLow: "कम",
    countries: "देश", showing: "दिखा रहा है", filterCategory: "श्रेणी", filterSource: "स्रोत",
    critical: "गंभीर", lastUpdate: "अंतिम अपडेट", viewSourceStatus: "स्रोत स्थिति देखें",
    backToTop: "शीर्ष पर वापस", tryChangingFilters: "अवधि या फ़िल्टर बदलने का प्रयास करें।",
    noTrendsCurrentFilters: "वर्तमान फ़िल्टर के साथ कोई रुझान नहीं मिला।", supportTool: "टूल के निरंतर सुधार का समर्थन करें", support: "सहयोग",
    verifiedPress: "सत्यापित प्रेस", scientificData: "वैज्ञानिक डेटा", internationalSource: "अंतर्राष्ट्रीय स्रोत", hotTopic: "गरम विषय",
    positive: "सकारात्मक", negative: "नकारात्मक", neutral: "तटस्थ",
    launch: "लॉन्च", crisis: "संकट", declaration: "बयान", sportsEvent: "खेल", scienceEvent: "विज्ञान", businessEvent: "व्यापार",
    startedAgo: "शुरू हुआ", peakAt: "शिखर",
    linkCopied: "लिंक कॉपी!", linkCopiedDesc: "वर्तमान फ़िल्टर वाला लिंक कॉपी किया गया।",
    loginRequired: "लॉगिन करें", loginRequiredDesc: "अलर्ट बनाने के लिए लॉगिन आवश्यक है।",
    error: "त्रुटि", alertCreated: "अलर्ट बनाया गया!", monitoring: "निगरानी",
    errorSummarize: "सारांश त्रुटि", tryAgain: "पुनः प्रयास करें।",
    filterByPlatform: "प्लेटफ़ॉर्म से फ़िल्टर", copyLinkFilters: "फ़िल्टर वाला लिंक कॉपी करें", createAlert: "अलर्ट बनाएं",
    tabDetails: "विवरण", tabContext: "संदर्भ", tabHistory: "इतिहास",
    general: "सामान्य", autoTranslated: "स्वचालित अनुवाद",
    loginTitle: "Global Talk Trends में साइन इन करें", loginSubtitle: "फ़िल्टर सहेजने और अलर्ट प्राप्त करने के लिए लॉगिन करें",
    continueWithGoogle: "Google से जारी रखें", continueWithApple: "Apple से जारी रखें", connecting: "कनेक्ट हो रहा है…",
    termsIntro: "जारी रखकर, आप सहमत होते हैं", termsOfUse: "उपयोग की शर्तें", privacyPolicy: "गोपनीयता नीति",
    allFeaturesFree: "सभी सुविधाएं मुफ्त हैं", enter: "लॉगिन",
  },
  ru: {
    trends: "Тренды", moreTrends: "Больше трендов", filters: "Фильтры",
    country: "Страна", period: "Период", category: "Категория", type: "Тип",
    global: "Глобально", lastHour: "Последний час", today: "Сегодня", thisWeek: "Эта неделя", thisMonth: "Этот месяц",
    all: "Все", politics: "Политика", entertainment: "Развлечения", technology: "Технологии",
    sports: "Спорт", culture: "Культура", business: "Бизнес/Финансы", science: "Наука",
    allMedia: "Все медиа", socialMedia: "Соцсети", press: "Пресса", searches: "Поиск (Google)",
    live: "в прямом эфире", peak: "ПИК", copied: "Скопировано!", updated: "Обновлено",
    about: "О проекте", aboutTitle: "Global-Talk-Trending",
    aboutDesc: "Монитор глобальных трендов в реальном времени. Мы агрегируем данные из YouTube, Reddit, Google Trends и NewsAPI.",
    map: "Карта", satellite: "Спутник", terrain: "Рельеф", timeline: "Таймлайн",
    clickToClose: "Нажмите, чтобы закрыть", trendCount: "тренды", loading: "Загрузка...",
    expandDetails: "Подробнее", evolution24h: "Динамика 24ч", share: "Поделиться", noTrends: "Нет трендов",
    heatmapDensity: "Плотность трендов", low: "Низкий", high: "Высокий",
    views: "просмотры", upvotes: "голоса", comments: "комментарии", interactions: "взаимодействия", likes: "лайки",
    officialSource: "Официальный источник", scientific: "Академический/Научный", international: "Международный", localPress: "Пресса",
    watchOn: "Смотреть на", viewOn: "Смотреть на", readOn: "Читать на", viewSource: "Оригинальный источник", summarizeAI: "Резюме с ИИ", analyzing: "Анализ...",
    aiSummary: "Резюме ИИ", impactHigh: "Высокий", impactMedium: "Средний", impactLow: "Низкий",
    countries: "Стран", showing: "Показано", filterCategory: "Категория", filterSource: "Источник",
    critical: "КРИТИЧЕСКИЕ", lastUpdate: "Последнее обновление", viewSourceStatus: "Статус источников",
    backToTop: "Наверх", tryChangingFilters: "Попробуйте изменить период или фильтры.",
    noTrendsCurrentFilters: "Не найдено трендов с текущими фильтрами.", supportTool: "Поддержите постоянное улучшение инструмента", support: "Поддержать",
    verifiedPress: "Проверенная пресса", scientificData: "Научные данные", internationalSource: "Международный источник", hotTopic: "ГОРЯЧАЯ ТЕМА",
    positive: "Позитивный", negative: "Негативный", neutral: "Нейтральный",
    launch: "Запуск", crisis: "Кризис", declaration: "Заявление", sportsEvent: "Спорт", scienceEvent: "Наука", businessEvent: "Бизнес",
    startedAgo: "Начало", peakAt: "Пик в",
    linkCopied: "Ссылка скопирована!", linkCopiedDesc: "Ссылка с текущими фильтрами скопирована.",
    loginRequired: "Войдите", loginRequiredDesc: "Для создания оповещений требуется вход.",
    error: "Ошибка", alertCreated: "Оповещение создано!", monitoring: "Мониторинг",
    errorSummarize: "Ошибка резюмирования", tryAgain: "Попробуйте снова.",
    filterByPlatform: "Фильтр по", copyLinkFilters: "Копировать ссылку с фильтрами", createAlert: "Создать оповещение",
    tabDetails: "Детали", tabContext: "Контекст", tabHistory: "История",
    general: "Общее", autoTranslated: "Автоматический перевод",
    loginTitle: "Войти в Global Talk Trends", loginSubtitle: "Войдите, чтобы сохранять фильтры и получать уведомления",
    continueWithGoogle: "Продолжить с Google", continueWithApple: "Продолжить с Apple", connecting: "Подключение…",
    termsIntro: "Продолжая, вы соглашаетесь с нашими", termsOfUse: "Условия использования", privacyPolicy: "Политика конфиденциальности",
    allFeaturesFree: "Все функции бесплатны", enter: "Войти",
  },
};

interface LanguageContextType {
  lang: LangCode;
  setLang: (lang: LangCode) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<LangCode>("pt");
  const t = useCallback((key: TranslationKey) => translations[lang]?.[key] || translations.pt[key] || key, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
